### ISSUE TITLE
Resizing doesn't work

### ISSUE THREAD

**Issue by MaxGuitet** [ryanhanwu/meteor-gridstack#1]
Hi,

I've been using gridstack and the resizing was working fine until recently. The drag handle is displayed but I can't manage to resize any of the boxes.
Is there a known issue with the latest version of Meteor?

Thanks for your help!

**Comment by ryanhanwu** [comment]
As far as I know, no. But when I'm using gridstack, i update the data myself after the view is relayouted or the resizing is done, haven't got any issue recently, can you reproduce your problem?

**Comment by MaxGuitet** [comment]
@ryanhanwu Sorry for the delay, I've been trying to replicate and understand. It turns out it comes from a conflict with another legacy package respondly:util.
Cheers!

**Comment by ryanhanwu** [comment]
@MaxGuitet No problem, thank you for your update.
